#ifndef TRUSTED_FLASH_H
#define TRUSTED_FLASH_H

#define LZ4_FRAME_SIZE	1024
#define FRAME_WIDTH	32
#define FRAME_HEIGHT 32
#define TRUSTED_FLASH_GAUSSIAN_KERNEL_SIZE	5
#define TRUSTED_FLASH_GAUSSIAN_KERNEL_SIGMA	0.8
#define TRUSTED_FLASH_ERODE_KERNEL_SIZE	3
#define TRUSTED_FLASH_DILATE_KERNEL_SIZE	3

#endif