include $(TA_DEV_KIT_DIR)/mk/conf.mk

SHLIBNAME = libtzio
SHLIBUUID = a6799c0f-518a-4107-87be-33757c906262
# add for native libtzio use pta io helper
CFG_USE_PTA_IO_HELPER ?=y
CFG_USE_FAT_PTR_CHECK ?=y
CFG_OVERHEAD_BENCHMARK ?=y
include ../ta_common.mk